/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LeaderboardEntry {
  'name' : string,
  'rank' : Rank,
  'points' : bigint,
}
export interface LiveStatus {
  'adSystem' : string,
  'referralSystem' : string,
  'leaderboard' : string,
  'backendConnection' : string,
  'authenticationSystem' : string,
  'overallStatus' : string,
}
export type Rank = [] | [bigint];
export type Time = bigint;
export interface UserProfile {
  'walletPoints' : bigint,
  'referralCode' : string,
  'successfulReferrals' : bigint,
  'name' : string,
  'lastLeaderboardTimestamp' : Time,
  'email' : string,
  'totalAdsWatched' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkEmailRegistered' : ActorMethod<[string], boolean>,
  'claimReferral' : ActorMethod<[string, string], bigint>,
  'createGmailAccount' : ActorMethod<[string, string], undefined>,
  'createUserProfile' : ActorMethod<[string, string, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLiveStatus' : ActorMethod<[], LiveStatus>,
  'getMiscStats' : ActorMethod<[], { 'adWatchCount' : bigint }>,
  'getUserLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getUserProfile' : ActorMethod<[Principal, string], [] | [UserProfile]>,
  'getWalletStats' : ActorMethod<
    [string],
    {
      'walletPoints' : bigint,
      'successfulReferrals' : bigint,
      'totalAdsWatched' : bigint,
    }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string, UserProfile], undefined>,
  'submitAdWatchHistory' : ActorMethod<[Time], boolean>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'updateUserProfile' : ActorMethod<[string, string, string], undefined>,
  'verifyGmailPassword' : ActorMethod<[string, string], boolean>,
  'watchAd' : ActorMethod<[string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];