/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'walletPoints' : IDL.Int,
  'referralCode' : IDL.Text,
  'successfulReferrals' : IDL.Int,
  'name' : IDL.Text,
  'lastLeaderboardTimestamp' : Time,
  'email' : IDL.Text,
  'totalAdsWatched' : IDL.Int,
});
export const LiveStatus = IDL.Record({
  'adSystem' : IDL.Text,
  'referralSystem' : IDL.Text,
  'leaderboard' : IDL.Text,
  'backendConnection' : IDL.Text,
  'authenticationSystem' : IDL.Text,
  'overallStatus' : IDL.Text,
});
export const Rank = IDL.Opt(IDL.Int);
export const LeaderboardEntry = IDL.Record({
  'name' : IDL.Text,
  'rank' : Rank,
  'points' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkEmailRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'claimReferral' : IDL.Func([IDL.Text, IDL.Text], [IDL.Int], []),
  'createGmailAccount' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLiveStatus' : IDL.Func([], [LiveStatus], ['query']),
  'getMiscStats' : IDL.Func(
      [],
      [IDL.Record({ 'adWatchCount' : IDL.Int })],
      ['query'],
    ),
  'getUserLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletStats' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'walletPoints' : IDL.Int,
          'successfulReferrals' : IDL.Int,
          'totalAdsWatched' : IDL.Int,
        }),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, UserProfile], [], []),
  'submitAdWatchHistory' : IDL.Func([Time], [IDL.Bool], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'verifyGmailPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'watchAd' : IDL.Func([IDL.Text], [IDL.Int], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'walletPoints' : IDL.Int,
    'referralCode' : IDL.Text,
    'successfulReferrals' : IDL.Int,
    'name' : IDL.Text,
    'lastLeaderboardTimestamp' : Time,
    'email' : IDL.Text,
    'totalAdsWatched' : IDL.Int,
  });
  const LiveStatus = IDL.Record({
    'adSystem' : IDL.Text,
    'referralSystem' : IDL.Text,
    'leaderboard' : IDL.Text,
    'backendConnection' : IDL.Text,
    'authenticationSystem' : IDL.Text,
    'overallStatus' : IDL.Text,
  });
  const Rank = IDL.Opt(IDL.Int);
  const LeaderboardEntry = IDL.Record({
    'name' : IDL.Text,
    'rank' : Rank,
    'points' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkEmailRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'claimReferral' : IDL.Func([IDL.Text, IDL.Text], [IDL.Int], []),
    'createGmailAccount' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLiveStatus' : IDL.Func([], [LiveStatus], ['query']),
    'getMiscStats' : IDL.Func(
        [],
        [IDL.Record({ 'adWatchCount' : IDL.Int })],
        ['query'],
      ),
    'getUserLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletStats' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'walletPoints' : IDL.Int,
            'successfulReferrals' : IDL.Int,
            'totalAdsWatched' : IDL.Int,
          }),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, UserProfile], [], []),
    'submitAdWatchHistory' : IDL.Func([Time], [IDL.Bool], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'verifyGmailPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'watchAd' : IDL.Func([IDL.Text], [IDL.Int], []),
  });
};

export const init = ({ IDL }) => { return []; };